//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tourist_VietripInsum_2023.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaiBao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BaiBao()
        {
            this.HinhAnhs = new HashSet<HinhAnh>();
        }
    
        public string MaBaiBao { get; set; }
        public string TieuDe { get; set; }
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> NgayDangBai { get; set; }
        public string MaHinhAnh { get; set; }
        public Nullable<bool> TrangThaiDuyet { get; set; }
        public Nullable<bool> TrangThaiBaiBao { get; set; }
        public string MaTL { get; set; }
        public string MaUser { get; set; }
    
        public virtual TheLoai TheLoai { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HinhAnh> HinhAnhs { get; set; }
        public virtual HinhAnh HinhAnh { get; set; }
    }
}
